services:
  ex_discourse:
    image: postgres:17.4-alpine3.21
    container_name: ex_discourse
    restart: unless-stopped
    ports:
      - "5433:5432" # Host port 5433 -> Container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ex_discourse_dev

volumes:
  postgres_data:
    driver: local
